skywalker/pizza/urls.py
from django.conf.urls import url
from pizza.views import (
     IngredientList,
     IngredientDetail,
     IngredientCreation,
     IngredientUpdate,
     IngredientDelete,
     PizzaBaseList,
     PizzaBaseDetail,
     PizzaBaseCreation,
     PizzaBaseUpdate,
     PizzaBaseDelete,
     PizzaList,
     PizzaDetail,
     PizzaCreation,
     PizzaUpdate,
     PizzaDelete,
)

urlpatterns = [
    url(r'^ingredient/$', IngredientList.as_view(), name='ingredient_list'),
    url(r'^ingredient/(?P<pk>\d+)$', IngredientDetail.as_view(), name='ingredient_detail'),
    url(r'^ingredient/new$', IngredientCreation.as_view(), name='ingredient_creation'),
    url(r'^ingredient/edit/(?P<pk>\d+)$', IngredientUpdate.as_view(), name='ingredient_edit'),
    url(r'^ingredient/delete/(?P<pk>\d+)$', IngredientDelete.as_view(), name='ingredient_delete'),

    url(r'^pizza-base/$', PizzaBaseList.as_view(), name='pizzabase_list'),
    url(r'^pizza-base/(?P<pk>\d+)$', PizzaBaseDetail.as_view(), name='pizzabase_detail'),
    url(r'^pizza-base/new$', PizzaBaseCreation.as_view(), name='pizzabase_creation'),
    url(r'^pizza-base/edit/(?P<pk>\d+)$', PizzaBaseUpdate.as_view(), name='pizzabase_edit'),
    url(r'^pizza-base/delete/(?P<pk>\d+)$', PizzaBaseDelete.as_view(), name='pizzabase_delete'),

    url(r'^pizza/$', PizzaList.as_view(), name='pizza_list'),
    url(r'^pizza/(?P<pk>\d+)$', PizzaDetail.as_view(), name='pizza_detail'),
    url(r'^pizza/new$', PizzaCreation.as_view(), name='pizza_creation'),
    url(r'^pizza/edit/(?P<pk>\d+)$', PizzaUpdate.as_view(), name='pizza_edit'),
    url(r'^pizza/delete/(?P<pk>\d+)$', PizzaDelete.as_view(), name='pizza_delete'),
]

skywalker/sale/urls.py
from django.conf.urls import url
from sale.views import (
    order,
    sales,
    sale_cancel,
    sale_approve,
    sale_order_create
)
from django.views.generic import TemplateView

urlpatterns = [
     url(r'^order/$', order, name='sale_order'),
     url(r'^sales/$', sales, name='sale_sales'),
     url(r'^sale/cancel/(?P<id>\d+)$', sale_cancel, name='sale_cancel'),
     url(r'^sale/approve/(?P<id>\d+)$', sale_approve, name='sale_approve'),
     url(r'^sale/order-create$', sale_order_create, name='sale_order_create'),

]

skywalker/skywalker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from accounts.views import login_view
from baseapp.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^console/', include('baseapp.urls')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^report/', include('report.urls', namespace='pizza')),

    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    
    # Bryan: I need this to verify my domain (c9) in Google
    url(r'^google9f65af6041bf39b4.html$',
        TemplateView.as_view(template_name="google9f65af6041bf39b4.html")),

    url(r'^$', IndexView.as_view(), name="index"),
    # App client - compras online
    url(r'^', include('client.urls', namespace='client')),
    
    # bryan: temporal
    url(r'^temp/$', TemplateView.as_view(template_name="client/base_purchases.html"), name='temp'),
    
    # App sale - ventas y despachos de pedidos
    url(r'^sale/', include('sale.urls', namespace='sale')),
]

## Se agregan este codigo para poder acceder a la imagen de la pizza que se encuentra
## en el directorio media/upload
# Django Tutorial for Beginners - 33 - Upload Files, https://www.youtube.com/watch?v=v5FWAxi5QqQ

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skywalker/pizza/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (Layout, Fieldset, ButtonHolder, Submit, Row,
                                 HTML, Field)
from django import forms
from baseapp.models import (
    Ingredient,
    PizzaBase,
    Pizza,
)


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('name', 'description', 'price')

    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'description',
            'price',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )


class PizzaBaseForm(forms.ModelForm):
    class Meta:
        model = PizzaBase
        fields = ('name', 'description', 'image', 'aditions')

    def __init__(self, *args, **kwargs):
        super(PizzaBaseForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'description',
            'image',
            'aditions',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ('price', 'size', 'pizza_base')

    def __init__(self, *args, **kwargs):
        super(PizzaForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'size',
            'price',
            'pizza_base',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

skywalker/pizza/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView)

from baseapp.models import (
    Ingredient,
    PizzaBase,
    Pizza
)

from baseapp.mixin import TitleContentPageMixin

from .forms import (
    IngredientForm,
    PizzaBaseForm,
    PizzaForm
)


# ENTITY INGREDIENT
class IngredientList(TitleContentPageMixin, ListView):
    model = Ingredient
    template_name = "ingredient/list.html"
    title_content = "Ingredients"

class IngredientDetail(TitleContentPageMixin,DetailView):
    model = Ingredient
    template_name = "ingredient/detail.html"
    title_content = "Detail Ingredient"

class IngredientCreation(TitleContentPageMixin, SuccessMessageMixin, CreateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient create successfully"
    title_content = "New Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create an ingredient"
        return context


class IngredientUpdate(TitleContentPageMixin, SuccessMessageMixin, UpdateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient edit successfully"
    title_content = "Update Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Edit an ingredient"
        return context


class IngredientDelete(TitleContentPageMixin, DeleteView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    template_name = "ingredient/confirm_delete.html"
    title_content = "Delete Ingredient"

# ENTITY PIZZA BASE
class PizzaBaseList(TitleContentPageMixin,ListView):
    model = PizzaBase
    template_name = "pizzaBase/list.html"
    title_content = "Base Pizzas"

class PizzaBaseDetail(TitleContentPageMixin, DetailView):
    model = PizzaBase
    template_name = "pizzaBase/detail.html"
    title_content = "Detail Base Pizza"

class PizzaBaseCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza create successfully"
    title_content = "New Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza edit successfully"
    title_content = "Update Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseDelete(TitleContentPageMixin, DeleteView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    template_name = "pizzaBase/confirm_delete.html"
    title_content = "Delete Base Pizza"

# ENTITY PIZZA
class PizzaList(TitleContentPageMixin,ListView):
    model = Pizza
    template_name = "pizza/list.html"
    title_content = "Pizzas"

class PizzaDetail(TitleContentPageMixin, DetailView):
    model = Pizza
    template_name = "pizza/detail.html"
    title_content = "Detail Pizza"

class PizzaCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza create successfully"
    title_content = "New Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza edit successfully"
    title_content = "Update Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaDelete(TitleContentPageMixin, DeleteView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    template_name = "pizza/confirm_delete.html"
    title_content = "Delete Pizza"

skywalker/pizza/templates/pizza/confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">{% csrf_token %}
        Are you sure you want to delete the pizza "{{ object.name }}"?
        <input class="btn btn-danger" type="submit" value="Delete"/>
    </form>

{% endblock %}

skywalker/pizza/templates/pizza/detail.html
{% extends 'base.html' %}

{% block new_action %}
    <a class="btn btn-default" href="{% url "pizza:pizza_edit" pizza.id %}">
        <i class="fa fa-edit"></i> Edit Pizza</a>
    <a class="btn btn-default" href="{% url "pizza:pizzabase_edit" pizza.pizza_base.id %}"><i
            class="fa fa-edit"></i> Edit Pizza Base</a>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-8 col-sm-12 col-md-8">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ pizza.pizza_base.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ pizza.pizza_base.description }}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{ pizza.price }}</td>
                </tr>
                <tr>
                    <th>Size</th>
                    <td>{{ pizza.size }}</td>
                </tr>
                <tr>
                    <th>Image</th>
                    <td><img class="img-responsive" width="400" height="300" src="{{ pizza.pizza_base.image.url }}">
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-lg-4 col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingredients</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        {% for adition in pizza.pizza_base.aditions.all %}
                            <tr>
                                <td>{{ adition.name }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

        </div>
    </div>




{% endblock %}

skywalker/pizza/templates/pizza/list.html
{% extends 'layout_list.html' %}

{% block new_action %}
    <a class="btn btn-default" href="{% url "pizza:pizza_creation" %}">
        <i class="fa fa-plus"></i> New Pizza</a>
{% endblock %}

{% block table %}
    <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
        <thead>
        <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Price</th>
            <th>Description</th>
            <th width="20%" data-hide="phone,tablet"></th>
        </tr>
        </thead>
        <tbody>
        {% for pizza in object_list %}
            <tr>
                <td>{{ pizza.pizza_base.name }}</td>
                <td>{{ pizza.size }}</td>
                <td>{{ pizza.price }}</td>
                <td>{{ pizza.pizza_base.description }}</td>
                <td class="text-align-center">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{% url "pizza:pizza_detail" pizza.id %}"><i
                                class="fa fa-eye"></i></a>
                        <a class="btn btn-default" href="{% url "pizza:pizza_edit" pizza.id %}"><i
                                class="fa fa-edit"></i></a>
                        <a class="btn btn-default" href="{% url "pizza:pizza_delete" pizza.id %}"><i
                                class="fa fa-trash"></i></a>
                    </div>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}