skywalker/baseapp/urls.py
# from django.conf.urls import url
# from baseapp.views import DashboardView


# urlpatterns = [
#     url(r'^$', DashboardView.as_view(), name='console-dashboard'),
# ]

skywalker/sale/urls.py
from django.conf.urls import url
from sale.views import (
    order,
    sales,
    sale_cancel,
    sale_approve,
    sale_order_create
)
from django.views.generic import TemplateView

urlpatterns = [
     url(r'^order/$', order, name='sale_order'),
     url(r'^sales/$', sales, name='sale_sales'),
     url(r'^sale/cancel/(?P<id>\d+)$', sale_cancel, name='sale_cancel'),
     url(r'^sale/approve/(?P<id>\d+)$', sale_approve, name='sale_approve'),
     url(r'^sale/order-create$', sale_order_create, name='sale_order_create'),

]

skywalker/skywalker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from accounts.views import login_view
from baseapp.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^console/', include('baseapp.urls')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^report/', include('report.urls', namespace='pizza')),

    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    
    # Bryan: I need this to verify my domain (c9) in Google
    url(r'^google9f65af6041bf39b4.html$',
        TemplateView.as_view(template_name="google9f65af6041bf39b4.html")),

    url(r'^$', IndexView.as_view(), name="index"),
    # App client - compras online
    url(r'^', include('client.urls', namespace='client')),
    
    # bryan: temporal
    url(r'^temp/$', TemplateView.as_view(template_name="client/base_purchases.html"), name='temp'),
    
    # App sale - ventas y despachos de pedidos
    url(r'^sale/', include('sale.urls', namespace='sale')),
]

## Se agregan este codigo para poder acceder a la imagen de la pizza que se encuentra
## en el directorio media/upload
# Django Tutorial for Beginners - 33 - Upload Files, https://www.youtube.com/watch?v=v5FWAxi5QqQ

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skywalker/baseapp/models.py
from django.db import models
from accounts.models import CustomUser as Client
from accounts.models import Employee

# Ingredient Class
class Ingredient(models.Model):
    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    name = models.CharField(max_length=200, null=False, blank=False)
    description = models.CharField(max_length=2000, null=True, blank=True)
    price = models.PositiveIntegerField(null=True)

    def __str__(self):
       return self.name

# Pizza base Class
class PizzaBase(models.Model):
    class Meta:
        verbose_name = "Pizza Base"
        verbose_name_plural = "Pizzas Base"

    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.CharField(max_length=300, null=False, blank=False)
    image = models.FileField(upload_to='upload/', blank=True, null=True)
    aditions = models.ManyToManyField(Ingredient)

    def __str__(self):
        return self.name

# Pizza Class
class Pizza(models.Model):
    class Meta:
        verbose_name = "Pizza"
        verbose_name_plural = "Pizzas"

    SMALL = 'SM'
    MEDIUM = 'MD'
    LARGE = 'LG'
    EXTRA_LARGE = 'XL'

    PIZZA_SIZE_CHOICES = (
        (SMALL, 'Small'),
        (MEDIUM, 'Medium'),
        (LARGE, 'Large'),
        (EXTRA_LARGE, 'Extra Large')
    )

    pizza_base = models.ForeignKey(PizzaBase)
    price = models.PositiveIntegerField(null=True)
    size = models.CharField(
        max_length=2,
        choices=PIZZA_SIZE_CHOICES,
        default=LARGE,
    )


# Sale Class
class Sale(models.Model):
    class Meta:
        verbose_name = 'Sale'
        verbose_name_plural = "Sales"

    PENDING = 'PE'
    DONE = 'DO'
    CANCEL = "CA"
    
    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (DONE, 'Done'),
        (CANCEL, 'Canceled')
    )
    
    salesman = models.ForeignKey(Employee, blank=True, null=True)
    client = models.ForeignKey(Client,  blank=True, null=True)
    date = models.DateTimeField()
    total = models.PositiveIntegerField(null=True)

    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default=PENDING,
    )


class Order(models.Model):
    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = "Orders"

    pizza = models.ForeignKey(Pizza)
    sale = models.ForeignKey(Sale, null=True)
    quantity = models.PositiveIntegerField(null=True)
    note = models.CharField(max_length=1000, null=True, blank=False)
    total = models.PositiveIntegerField(null=True)

skywalker/baseapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.contrib.auth import logout


class IndexView(View):
    """
    Author: Bryan Tabarez
    Render the template if the user is authenticated, and sets the session
    variable 'user_role'
    """
    
    def dispatch(self,request,*args,**kwargs):
        user = request.user
        if user.is_authenticated() and user.is_active and not user.is_staff:
            # Session variable available in all templates
            user_role = ""
            if hasattr(user, "employee"):
                user_role = user.employee.employee_type
                request.session["user_role"] = user_role
                return redirect('accounts:user_list')
            else:
                user_role = "client"
                # redirect to main page of client <-----------------------------
            request.session["user_role"] = user_role
            return redirect('login')

        else:
            logout(request)
            # return redirect('accounts:login')
            return redirect('client:client_index')


index = IndexView.as_view()

skywalker/baseapp/templates/includes/navigation.html
{% load static %}
<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">
    <span> <!-- User image size is adjusted inside CSS, it should stay as is -->

      <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
        <img src="{% static "baseapp/img/avatars/sunny.png" %}" alt="me" class="online" />
        <small>
          {{ user.email|lower }}
        </small>
        <i class="fa fa-angle-down"></i>
      </a>

    </span>
  </div>
  <!-- end user info -->

  <!-- NAVIGATION : This navigation is also responsive

  To make this navigation dynamic please make sure to link the node
  (the reference to the nav > ul) after page load. Or the navigation
  will not initialize.
  -->

  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->
    <ul>
      <li>
        <a href="#">role {{ request.session.user_role|capfirst }}</a>
      </li>
    </ul>
    {% if request.session.user_role  == "client" %}
      {% include "includes/navlist_client.html" %}
    {% elif request.session.user_role == "administrator" %}
      {% include "includes/navlist_admin.html" %}
    {% elif request.session.user_role == "employee" %}
      {% include "includes/navlist_employee.html" %}
    {% endif %}

    {% block nav-list %}
		{% endblock %}

  </nav>

  <span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>

</aside>

skywalker/baseapp/templates/includes/navlist_admin.html
<ul>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i> <span class="menu-item-parent">Graphs</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li>
        <a href="ajax/flot.html">Flot Chart</a>
      </li>
      <li>
        <a href="ajax/morris.html">Morris Charts</a>
      </li>
      <li>
        <a href="ajax/sparkline-charts.html">Sparklines</a>
      </li>
      <li>
        <a href="ajax/easypie-charts.html">EasyPieCharts</a>
      </li>
      <li>
        <a href="ajax/dygraphs.html">Dygraphs</a>
      </li>
      <li>
        <a href="ajax/chartjs.html">Chart.js</a>
      </li>
      <li>
        <a href="ajax/hchartable.html">HighchartTable <span class="badge pull-right inbox-badge bg-color-yellow">new</span></a>
      </li>
    </ul>
  </li>
</ul>

skywalker/baseapp/templates/includes/navlist_client.html
{% with url_name=request.resolver_match.url_name namespace=request.resolver_match.namespace %}

<ul>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-id-card-o"></i> <span class="menu-item-parent">My account</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li class="{% if url_name == 'socialaccount_connections' %}active{% endif %}">
        <a href="{% url 'socialaccount_connections' %}">Social connections</a>
      </li>
      <li class="{% if url_name == 'account_reset_password' %}active{% endif %}">
        <a href="{% url 'account_reset_password' %}">Reset password</a>
      </li>
    </ul>
  </li>
  
</ul>

{% endwith %}

skywalker/baseapp/templates/includes/navlist_employee.html
{% with url_name=request.resolver_match.url_name namespace=request.resolver_match.namespace %}

<ul>
  <li class="{% if namespace == 'tenants' %}active{% endif %}">
		<a href="{% url 'tenants:list' %}"><i class="fa fa-lg fa-fw fa-code-fork"></i> <span class="menu-item-parent">Tenants</span></a>
	</li>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-id-card-o"></i> <span class="menu-item-parent">My account</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li class="{% if url_name == 'socialaccount_connections' %}active{% endif %}">
        <a href="{% url 'socialaccount_connections' %}">Social connections</a>
      </li>
      <li class="{% if url_name == 'account_reset_password' %}active{% endif %}">
        <a href="{% url 'account_reset_password' %}">Reset password</a>
      </li>
    </ul>
  </li>
  <li class="{% if namespace == 'accounts' %}open{% endif %}">
    <a href="#"><i class="fa fa-lg fa-fw fa-user"></i> <span class="menu-item-parent">Users</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li class="{% if url_name == 'user_list' %}active{% endif %}">
        <a href="{% url 'accounts:user_list' %}">Clients</a>
      </li>
      <li class="{% if url_name == 'employee_list' %}active{% endif %}">
        <a href="{% url 'accounts:employee_list' %}">Employees</a>
      </li>
    </ul>
  </li>
  <li class="{% if namespace == 'pizza' %}open{% endif %}">
    <a href="#"><i class="fa fa-lg fa-fw fa-pie-chart"></i> <span class="menu-item-parent">Pizza management</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li class="{% if url_name == 'ingredient_list' %}active{% endif %}">
        <a href="{% url 'pizza:ingredient_list' %}">Ingredients</a>
      </li>
      <li class="{% if url_name == 'pizzabase_list' %}active{% endif %}">
        <a href="{% url 'pizza:pizzabase_list' %}">Pizzas (base)</a>
      </li>
      <li class="{% if url_name == 'pizza_list' %}active{% endif %}">
        <a href="{% url 'pizza:pizza_list' %}">Pizzas</a>
      </li>
    </ul>
  </li>
  <li class="{% if namespace == 'sale' %}open{% endif %}">
    <a href="#"><i class="fa fa-lg fa-fw fa-pie-chart"></i> <span class="menu-item-parent">Sales</span><b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b></a>
    <ul>
      <li class="{% if url_name == 'sale_order' %}active{% endif %}">
        <a href="{% url 'sale:sale_order' %}">Order</a>
      </li>
      <li class="{% if url_name == 'sale_sales' %}active{% endif %}">
        <a href="{% url 'sale:sale_sales' %}">Sales</a>
      </li>
    </ul>
  </li>
</ul>


{% endwith %} 