skywalker/orders/urls.py
from django.conf.urls import url
from orders.views import (
    PizzaBaseproductsViewList,
    OrderList,
    OrderCreation,
    OrderDelete,
    OrderUpdate,
    OrderDetail,
     IngredientList,
     IngredientDetail,
     IngredientCreation,
     IngredientUpdate,
     IngredientDelete,
     PizzaBaseList,
     PizzaBaseDetail,
     PizzaBaseCreation,
     PizzaBaseUpdate,
     PizzaBaseDelete,
     PizzaList,
     PizzaDetail,
     PizzaCreation,
     PizzaUpdate,
     PizzaDelete,
)

urlpatterns = [

    url(r'^ingredient/$', IngredientList.as_view(), name='ingredient_list'),
    url(r'^ingredient/(?P<pk>\d+)$', IngredientDetail.as_view(), name='ingredient_detail'),
    url(r'^ingredient/new$', IngredientCreation.as_view(), name='ingredient_creation'),
    url(r'^ingredient/edit/(?P<pk>\d+)$', IngredientUpdate.as_view(), name='ingredient_edit'),
    url(r'^ingredient/delete/(?P<pk>\d+)$', IngredientDelete.as_view(), name='ingredient_delete'),
    #PizzaBaseproductsViewList
    url(r'^PizzaBaseproductsView/$',   PizzaBaseproductsViewList.as_view(), name='PizzaBaseproductsView_list'),
    url(r'^order/$',                   OrderList.as_view(),                 name='order_list'),
    url(r'^order/new$',                OrderCreation.as_view(),             name='order_creation'),
    url(r'^order/delete/(?P<pk>\d+)$', OrderDelete.as_view(),               name='order_delete'),
    url(r'^order/edit/(?P<pk>\d+)$',   OrderUpdate.as_view(),               name='order_edit'),
    url(r'^order/(?P<pk>\d+)$',        OrderDetail.as_view(),               name='order_detail'),


    url(r'^pizza-base-list/$', PizzaBaseList.as_view(), name='pizzabase_list'),
    url(r'^pizza-base-list/(?P<pk>\d+)$', PizzaBaseDetail.as_view(), name='pizzabase_detail'),
    url(r'^pizza-base/new$', PizzaBaseCreation.as_view(), name='pizzabase_creation'),
    url(r'^pizza-base/edit/(?P<pk>\d+)$', PizzaBaseUpdate.as_view(), name='pizzabase_edit'),
    url(r'^pizza-base/delete/(?P<pk>\d+)$', PizzaBaseDelete.as_view(), name='pizzabase_delete'),

    url(r'^pizza/$', PizzaList.as_view(), name='pizza_list'),
    url(r'^pizza/(?P<pk>\d+)$', PizzaDetail.as_view(), name='pizza_detail'),
    url(r'^pizza/new$', PizzaCreation.as_view(), name='pizza_creation'),
    url(r'^pizza/edit/(?P<pk>\d+)$', PizzaUpdate.as_view(), name='pizza_edit'),
    url(r'^pizza/delete/(?P<pk>\d+)$', PizzaDelete.as_view(), name='pizza_delete'),
]

skywalker/sale/urls.py
from django.conf.urls import url
from sale.views import (
    order,
    sales,
    sale_cancel,
    sale_approve,
    sale_order_create
)
from django.views.generic import TemplateView

urlpatterns = [
     url(r'^order/$', order, name='sale_order'),
     url(r'^sales/$', sales, name='sale_sales'),
     url(r'^sale/cancel/(?P<id>\d+)$', sale_cancel, name='sale_cancel'),
     url(r'^sale/approve/(?P<id>\d+)$', sale_approve, name='sale_approve'),
     url(r'^sale/order-create$', sale_order_create, name='sale_order_create'),

]

skywalker/skywalker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from accounts.views import login_view
from baseapp.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^console/', include('baseapp.urls')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^report/', include('report.urls', namespace='pizza')),

    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    
    # Bryan: I need this to verify my domain (c9) in Google
    url(r'^google9f65af6041bf39b4.html$',
        TemplateView.as_view(template_name="google9f65af6041bf39b4.html")),

    url(r'^$', IndexView.as_view(), name="index"),
    # App client - compras online
    url(r'^', include('client.urls', namespace='client')),
    
    # bryan: temporal
    url(r'^temp/$', TemplateView.as_view(template_name="client/base_purchases.html"), name='temp'),
    
    # App sale - ventas y despachos de pedidos
    url(r'^sale/', include('sale.urls', namespace='sale')),
]

## Se agregan este codigo para poder acceder a la imagen de la pizza que se encuentra
## en el directorio media/upload
# Django Tutorial for Beginners - 33 - Upload Files, https://www.youtube.com/watch?v=v5FWAxi5QqQ

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skywalker/orders/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (Layout, Fieldset, ButtonHolder, Submit, Row,
                                 HTML, Field)
from django import forms
from baseapp.models import (
    Order,
    Ingredient,
    PizzaBase,
    Pizza,
)

# FORM ORDER
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('pizza', 'ingredients', 'note')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'pizza',
            'ingredients',
            'note',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

class IngredientForm(forms.ModelForm):

    class Meta:
        model = Ingredient
        fields = ('name', 'description', 'price')

    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'description',
            'price',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

class PizzaBaseForm(forms.ModelForm):
    class Meta:
        model = PizzaBase
        fields = ('name', 'description', 'image', 'aditions')

    def __init__(self, *args, **kwargs):
        super(PizzaBaseForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'description',
            'image',
            'aditions',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ('price', 'size', 'pizza_base')

    def __init__(self, *args, **kwargs):
        super(PizzaForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'size',
            'price',
            'pizza_base',
            ButtonHolder(
                HTML('<div class="form-actions">'),
                Submit('Submit', 'Save', css_class='button btn-primary'),
                HTML('</div>'),
            )
        )

skywalker/orders/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView)

from baseapp.models import (
    Order,
    Ingredient,
    PizzaBase,
    Pizza
)

from baseapp.mixin import TitleContentPageMixin

from .forms import (
    OrderForm,
    IngredientForm,
    PizzaBaseForm,
    PizzaForm
)

# ENTITY ORDER
#products-view
class PizzaBaseproductsViewList(TitleContentPageMixin, ListView):
    model = PizzaBase
    template_name = "orders/products-view.html"
    title_content = "orders"

class OrderList(TitleContentPageMixin, ListView):
    model = Order
    template_name = "orders/list.html"
    title_content = "orders"

class OrderCreation(TitleContentPageMixin, SuccessMessageMixin, CreateView):
    model = Order
    #success_url = reverse_lazy('orders:order_list')
    form_class = OrderForm
    template_name = "object/object_form.html"
    success_message = "Order create successfully"
    title_content = "New Order"

    def get_context_data(self, **kwargs):
        context = super(OrderCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create an ingredient"
        return context

class OrderDelete(TitleContentPageMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('orders:order_list')
    template_name = "orders/confirm_delete.html"
    title_content = "Delete Ingredient"

class OrderUpdate(TitleContentPageMixin, SuccessMessageMixin, UpdateView):
    model = Order
    success_url = reverse_lazy('orders:order_list')
    form_class = OrderForm
    template_name = "object/object_form.html"
    success_message = "Order edit successfully"
    title_content = "Update Order"

    def get_context_data(self, **kwargs):
        context = super(OrderUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Edit an ingredient"
        return context

class OrderDetail(TitleContentPageMixin,DetailView):
    model = Order
    template_name = "orders/detail.html"
    title_content = "Detail Order"


# ENTITY INGREDIENT
class IngredientList(TitleContentPageMixin, ListView):
    model = Ingredient
    template_name = "ingredient/list.html"
    title_content = "Ingredients"

class IngredientDetail(TitleContentPageMixin,DetailView):
    model = Ingredient
    template_name = "ingredient/detail_1.html"
    title_content = "Detail Ingredient"

class IngredientCreation(TitleContentPageMixin, SuccessMessageMixin, CreateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient create successfully"
    title_content = "New Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create an ingredient"
        return context

class IngredientUpdate(TitleContentPageMixin, SuccessMessageMixin, UpdateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient edit successfully"
    title_content = "Update Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Edit an ingredient"
        return context

class IngredientDelete(TitleContentPageMixin, DeleteView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    template_name = "ingredient/confirm_delete.html"
    title_content = "Delete Ingredient"

# ENTITY PIZZA BASE
class PizzaBaseList(TitleContentPageMixin,ListView):
    model = Pizza
    template_name = "orders/list_1.html"
    title_content = "Pizza List"

class PizzaBaseDetail(TitleContentPageMixin, DetailView):
    model = PizzaBase
    template_name = "orders/detail_1.html"
    title_content = "Detail Base Pizza"

class PizzaBaseCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza create successfully"
    title_content = "New Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza edit successfully"
    title_content = "Update Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseDelete(TitleContentPageMixin, DeleteView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    template_name = "pizzaBase/confirm_delete.html"
    title_content = "Delete Base Pizza"

# ENTITY PIZZA
class PizzaList(TitleContentPageMixin,ListView):
    model = Pizza
    template_name = "pizza/list.html"
    title_content = "Pizzas"

class PizzaDetail(TitleContentPageMixin, DetailView):
    model = Pizza
    template_name = "pizza/detail.html"
    title_content = "Detail Pizza"

class PizzaCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza create successfully"
    title_content = "New Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza edit successfully"
    title_content = "Update Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaDelete(TitleContentPageMixin, DeleteView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    template_name = "pizza/confirm_delete.html"
    title_content = "Delete Pizza"

skywalker/orders/templates/orders/confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">{% csrf_token %}
        Are you sure you want to delete the order "{{ object.name }}"?
        <input class="btn btn-danger" type="submit" value="Delete"/>
    </form>

{% endblock %}

skywalker/orders/templates/orders/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-3 col-sm-12 col-md-3">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ order.pizza.pizza_base.name }}</td>
                </tr>

                <tr>
                    <th>Image</th>
                    <script>
                    console.log("imagen: "+"{{ order.pizza.pizza_base.image.url }}");
                    console.log("imagen: "+"{{ order.pizza.pizza_base.image }}");
                    console.log("imagen: "+"{{ order.pizza.pizza_base }}");
                    </script>
                    <td><img class="img-responsive" width="400" height="300" src="{{ order.pizza.pizza_base.image.url }}"></td>
                </tr>

                <tr>
                    <th>Note</th>
                    <td>{{ order.note }}</td>
                </tr>


            </table>
        </div>
        <div class="col-lg-4 col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingredients</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        <script>console.log("nombre ingredientes:   "+"{{ order.ingredients.all }}")</script>
                        <script>console.log("nombre ingredientes:   "+"{{ order.ingredients }}")</script>
                        <script>console.log("nombre ingredientes:   "+"{{ ingredient.name }}")</script>

                        {% for ingredient in order.ingredients.all %}
                        <script>console.log("nombre ingredientes:   "+"{{ ingredient.name }}")</script>
                        <tr>
                            <td>{{ ingredient.name }}</td>
                        </tr>
                        {% endfor %}

                        {% for aditions in order.pizza.pizza_base.aditions.all %}
                        <script>console.log("nombre aditions:   "+"{{ aditions.name }}")</script>
                        <tr>
                            <td>{{ aditions.name }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

        </div>
    </div>




{% endblock %}

skywalker/orders/templates/orders/detail_1.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-lg-3 col-sm-12 col-md-3">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ pizzabase.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ pizzabase.description }}</td>
                </tr>

                <tr>
                    <th>Image</th>
                    <td><img class="img-responsive" width="400" height="300" src="{{ pizzabase.image.url }}"></td>
                </tr>
            </table>
        </div>
        <div class="col-lg-4 col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingredients</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        {% for adition in pizzabase.aditions.all %}
                            <tr>
                                <td>{{ adition.name }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

        </div>
    </div>




{% endblock %}

skywalker/orders/templates/orders/list_1.html
{% extends 'layout_list.html' %}

{% block new_action %}
{% endblock %}

{% block table %}

<!-- --------------------------------------------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------------------------------------------- -->

<!-- widget grid -->
<section id="widget-grid" class="">

    <!-- row -->

    <div class="row">
        <!-- ------------------------------------------------------------------------------------------------------- -->
        <div class="col-sm-6 col-md-6 col-lg-6">
            <!-- product -->
            <!--
            <div class="product-content product-wrap clearfix">
                <div class="row">
                    <div class="col-md-5 col-sm-12 col-xs-12">
                        <div class="product-image">
                            <img src="img/demo/e-comm/1.png" alt="194x228" class="img-responsive">
												<span class="tag2 hot">
													HOT
												</span>
                        </div>
                    </div>
                    <div class="col-md-7 col-sm-12 col-xs-12">
                        <div class="product-deatil">
                            <h5 class="name">
                                <a href="#">
                                    Product Name Title Here <span>Category</span>
                                </a>
                            </h5>

                            <p class="price-container">
                                <span>$99</span>
                            </p>
                            <span class="tag1"></span>
                        </div>
                        <div class="description">
                            <p>Proin in ullamcorper lorem. Maecenas eu ipsum </p>
                        </div>
                        <div class="product-info smart-form">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <a href="javascript:void(0);" class="btn btn-success">Add to cart</a>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="rating">
                                        <input type="radio" name="stars-rating" id="stars-rating-5">
                                        <label for="stars-rating-5"><i class="fa fa-star"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-4">
                                        <label for="stars-rating-4"><i class="fa fa-star"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-3">
                                        <label for="stars-rating-3"><i class="fa fa-star text-primary"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-2">
                                        <label for="stars-rating-2"><i class="fa fa-star text-primary"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-1">
                                        <label for="stars-rating-1"><i class="fa fa-star text-primary"></i></label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            -->
            <!-- end product -->
        </div>

        <div class="col-sm-6 col-md-6 col-lg-6">
            <!-- product -->
            <!--
            <div class="product-content product-wrap clearfix">
                <div class="row">
                    <div class="col-md-5 col-sm-12 col-xs-12">
                        <div class="product-image">
                            <img src="img/demo/e-comm/2.png" alt="194x228" class="img-responsive">
												<span class="tag2 sale">
													Sale
												</span>
                        </div>
                    </div>
                    <div class="col-md-7 col-sm-12 col-xs-12">
                        <div class="product-deatil">
                            <h5 class="name">
                                <a href="#">
                                    Product Name Title Here <span>Category</span>
                                </a>
                            </h5>

                            <p class="price-container">
                                <span>$109</span>
                            </p>
                            <span class="tag1"></span>
                        </div>
                        <div class="description">
                            <p>Proin in ullamcorper lorem. Maecenas eu ipsum </p>
                        </div>
                        <div class="product-info smart-form">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6"><a href="javascript:void(0);"
                                                                           class="btn btn-success">Add to cart</a></div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <div class="rating">

                                        <input type="radio" name="stars-rating" id="stars-rating-5">
                                        <label for="stars-rating-5"><i class="fa fa-star"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-4">
                                        <label for="stars-rating-4"><i class="fa fa-star"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-3">
                                        <label for="stars-rating-3"><i class="fa fa-star text-primary"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-2">
                                        <label for="stars-rating-2"><i class="fa fa-star text-primary"></i></label>
                                        <input type="radio" name="stars-rating" id="stars-rating-1">
                                        <label for="stars-rating-1"><i class="fa fa-star text-primary"></i></label>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            -->
            <!-- end product -->
        </div>

        <!-- ------------------------------------------------------------------------------------------------------- -->
        {% for Pizza in object_list %}

        <div class="col-sm-6 col-md-6 col-lg-4">
            <!-- product -->
            <div class="product-content product-wrap clearfix">
                <div class="row">
                    <div class="col-md-5 col-sm-12 col-xs-12">
                        <div class="product-image">
                            <img src="{{ Pizza.pizza_base.image.url }}" alt="194x228" class="img-responsive">
                            <!--
                            <span class="tag2 hot">
                                HOT
                            </span>
                            -->
                            <span class="tag2 sale">
                                Sale
                            </span>
                        </div>
                    </div>
                    <div class="col-md-7 col-sm-12 col-xs-12">
                        <div class="product-deatil">
                            <h5 class="name">
                                <a href="#">
                                    {{ Pizza.pizza_base.name }} <span> size: {{ Pizza.size }} </span>
                                </a>
                            </h5>

                            <p class="price-container">
                                <span>${{ Pizza.price }}</span>
                            </p>
                            <span class="tag1"></span>
                        </div>
                        <div class="description">
                            <p> {{ Pizza.pizza_base.description }} </p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end product -->
        </div>
        {% endfor %}

        <!-- ------------------------------------------------------------------------------------------------------------------------ -->
        <div class="col-sm-12 text-center">
            <a href="javascript:void(0);" class="btn btn-primary btn-lg">Load more <i class="fa fa-arrow-down"></i></a>
        </div>

    </div>
    <!-- end row -->

</section>
<!-- end widget grid -->

<!-- --------------------------------------------------------------------------------------------------------------- -->
<!-- --------------------------------------------------------------------------------------------------------------- -->

<!--
    <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
        <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th width="20%" data-hide="phone,tablet"></th>
        </tr>
        </thead>
        <tbody>
        {% for pizzabase in object_list %}
            <tr>
                <td>{{ pizzabase.name }}</td>
                <td>{{ pizzabase.description }}</td>
                <td class="text-align-center">
                    <div class="btn-group">
                        <a class="btn btn-default" href="{% url "pizza:pizzabase_detail" pizzabase.id %}"><i
                                class="fa fa-eye"></i></a>
                        <a class="btn btn-default" href="{% url "pizza:pizzabase_edit" pizzabase.id %}"><i
                                class="fa fa-edit"></i></a>
                        <a class="btn btn-default" href="{% url "pizza:pizzabase_delete" pizzabase.id %}"><i
                                class="fa fa-trash"></i></a>
                    </div>
                </td>

            </tr>
        {% endfor %}

        </tbody>
    </table>
-->

{% for pizzabase in object_list %}

<!--
    <div class="col-lg-3 col-sm-12 col-md-3">
        <label> {{ pizzabase.name }} </label>
        <script>
            console.log ("{{  pizzabase.image.url }}");
        </script>
        <img class="img-responsive" width="400" height="300" src="{{ pizzabase.image.url }}">
    </div>
-->

<!--
        <div class="col-lg-3 col-sm-12 col-md-3">

            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <td>{{ pizzabase.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ pizzabase.description }}</td>
                </tr>
                <tr>
                    <th>Image</th>
                    <td><img class="img-responsive" width="400" height="300" src="{{ pizzabase.image.url }}"></td>
                </tr>
            </table>
        </div>
-->
{% endfor %}

{% endblock %}