skywalker/client/urls.py
from django.conf.urls import url
from client.views import (
    index,
    order,
    order_create,
    order_cancel,
    history
)

urlpatterns = [
     url(r'^index/$', index, name='client_index'),
     url(r'^order/$', order, name='client_order'),
     url(r'^order/create/$', order_create, name='client_order_create'),
     url(r'^history/$', history, name='client_history'),
     url(r'^order/cancel/(?P<id>\d+)$', order_cancel, name='client_order_cancel'),
     
]

skywalker/orders/urls.py
from django.conf.urls import url
from orders.views import (
    PizzaBaseproductsViewList,
    OrderList,
    OrderCreation,
    OrderDelete,
    OrderUpdate,
    OrderDetail,
     IngredientList,
     IngredientDetail,
     IngredientCreation,
     IngredientUpdate,
     IngredientDelete,
     PizzaBaseList,
     PizzaBaseDetail,
     PizzaBaseCreation,
     PizzaBaseUpdate,
     PizzaBaseDelete,
     PizzaList,
     PizzaDetail,
     PizzaCreation,
     PizzaUpdate,
     PizzaDelete,
)

urlpatterns = [

    url(r'^ingredient/$', IngredientList.as_view(), name='ingredient_list'),
    url(r'^ingredient/(?P<pk>\d+)$', IngredientDetail.as_view(), name='ingredient_detail'),
    url(r'^ingredient/new$', IngredientCreation.as_view(), name='ingredient_creation'),
    url(r'^ingredient/edit/(?P<pk>\d+)$', IngredientUpdate.as_view(), name='ingredient_edit'),
    url(r'^ingredient/delete/(?P<pk>\d+)$', IngredientDelete.as_view(), name='ingredient_delete'),
    #PizzaBaseproductsViewList
    url(r'^PizzaBaseproductsView/$',   PizzaBaseproductsViewList.as_view(), name='PizzaBaseproductsView_list'),
    url(r'^order/$',                   OrderList.as_view(),                 name='order_list'),
    url(r'^order/new$',                OrderCreation.as_view(),             name='order_creation'),
    url(r'^order/delete/(?P<pk>\d+)$', OrderDelete.as_view(),               name='order_delete'),
    url(r'^order/edit/(?P<pk>\d+)$',   OrderUpdate.as_view(),               name='order_edit'),
    url(r'^order/(?P<pk>\d+)$',        OrderDetail.as_view(),               name='order_detail'),


    url(r'^pizza-base-list/$', PizzaBaseList.as_view(), name='pizzabase_list'),
    url(r'^pizza-base-list/(?P<pk>\d+)$', PizzaBaseDetail.as_view(), name='pizzabase_detail'),
    url(r'^pizza-base/new$', PizzaBaseCreation.as_view(), name='pizzabase_creation'),
    url(r'^pizza-base/edit/(?P<pk>\d+)$', PizzaBaseUpdate.as_view(), name='pizzabase_edit'),
    url(r'^pizza-base/delete/(?P<pk>\d+)$', PizzaBaseDelete.as_view(), name='pizzabase_delete'),

    url(r'^pizza/$', PizzaList.as_view(), name='pizza_list'),
    url(r'^pizza/(?P<pk>\d+)$', PizzaDetail.as_view(), name='pizza_detail'),
    url(r'^pizza/new$', PizzaCreation.as_view(), name='pizza_creation'),
    url(r'^pizza/edit/(?P<pk>\d+)$', PizzaUpdate.as_view(), name='pizza_edit'),
    url(r'^pizza/delete/(?P<pk>\d+)$', PizzaDelete.as_view(), name='pizza_delete'),
]

skywalker/sale/urls.py
from django.conf.urls import url
from sale.views import (
    order,
    sales,
    sale_cancel,
    sale_approve,
    sale_order_create
)
from django.views.generic import TemplateView

urlpatterns = [
     url(r'^order/$', order, name='sale_order'),
     url(r'^sales/$', sales, name='sale_sales'),
     url(r'^sale/cancel/(?P<id>\d+)$', sale_cancel, name='sale_cancel'),
     url(r'^sale/approve/(?P<id>\d+)$', sale_approve, name='sale_approve'),
     url(r'^sale/order-create$', sale_order_create, name='sale_order_create'),

]

skywalker/skywalker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from accounts.views import login_view
from baseapp.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^console/', include('baseapp.urls')),
    url(r'^pizza/', include('pizza.urls', namespace='pizza')),
    url(r'^report/', include('report.urls', namespace='pizza')),

    url(r'^login/$', login_view, name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    
    # Bryan: I need this to verify my domain (c9) in Google
    url(r'^google9f65af6041bf39b4.html$',
        TemplateView.as_view(template_name="google9f65af6041bf39b4.html")),

    url(r'^$', IndexView.as_view(), name="index"),
    # App client - compras online
    url(r'^', include('client.urls', namespace='client')),
    
    # bryan: temporal
    url(r'^temp/$', TemplateView.as_view(template_name="client/base_purchases.html"), name='temp'),
    
    # App sale - ventas y despachos de pedidos
    url(r'^sale/', include('sale.urls', namespace='sale')),
]

## Se agregan este codigo para poder acceder a la imagen de la pizza que se encuentra
## en el directorio media/upload
# Django Tutorial for Beginners - 33 - Upload Files, https://www.youtube.com/watch?v=v5FWAxi5QqQ

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skywalker/baseapp/models.py
from django.db import models
from accounts.models import CustomUser as Client
from accounts.models import Employee

# Ingredient Class
class Ingredient(models.Model):
    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    name = models.CharField(max_length=200, null=False, blank=False)
    description = models.CharField(max_length=2000, null=True, blank=True)
    price = models.PositiveIntegerField(null=True)

    def __str__(self):
       return self.name

# Pizza base Class
class PizzaBase(models.Model):
    class Meta:
        verbose_name = "Pizza Base"
        verbose_name_plural = "Pizzas Base"

    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.CharField(max_length=300, null=False, blank=False)
    image = models.FileField(upload_to='upload/', blank=True, null=True)
    aditions = models.ManyToManyField(Ingredient)

    def __str__(self):
        return self.name

# Pizza Class
class Pizza(models.Model):
    class Meta:
        verbose_name = "Pizza"
        verbose_name_plural = "Pizzas"

    SMALL = 'SM'
    MEDIUM = 'MD'
    LARGE = 'LG'
    EXTRA_LARGE = 'XL'

    PIZZA_SIZE_CHOICES = (
        (SMALL, 'Small'),
        (MEDIUM, 'Medium'),
        (LARGE, 'Large'),
        (EXTRA_LARGE, 'Extra Large')
    )

    pizza_base = models.ForeignKey(PizzaBase)
    price = models.PositiveIntegerField(null=True)
    size = models.CharField(
        max_length=2,
        choices=PIZZA_SIZE_CHOICES,
        default=LARGE,
    )


# Sale Class
class Sale(models.Model):
    class Meta:
        verbose_name = 'Sale'
        verbose_name_plural = "Sales"

    PENDING = 'PE'
    DONE = 'DO'
    CANCEL = "CA"
    
    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (DONE, 'Done'),
        (CANCEL, 'Canceled')
    )
    
    salesman = models.ForeignKey(Employee, blank=True, null=True)
    client = models.ForeignKey(Client,  blank=True, null=True)
    date = models.DateTimeField()
    total = models.PositiveIntegerField(null=True)

    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default=PENDING,
    )


class Order(models.Model):
    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = "Orders"

    pizza = models.ForeignKey(Pizza)
    sale = models.ForeignKey(Sale, null=True)
    quantity = models.PositiveIntegerField(null=True)
    note = models.CharField(max_length=1000, null=True, blank=False)
    total = models.PositiveIntegerField(null=True)

skywalker/client/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from baseapp.models import Pizza, Sale, Order
from accounts.models import Employee
from accounts.models import CustomUser as User
#from django.contrib.auth import get_user_model as User
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from datetime import datetime


def index(request):
    pizzas = Pizza.objects.all()
    return render(request, 'client/index.html', {'pizzas': pizzas})

@login_required()
def order(request):
    pizzas = Pizza.objects.all()
    return render(request, 'client/order.html', {'pizzas': pizzas})

@login_required()
def order_create(request):
    if request.method == 'POST':
        client = request.user  
        pizzas_data = request.POST.getlist('products_selected[]')
        sale_create = Sale(
            client=client,
            date=datetime.now()
        )
        sale_create.save()
        total_global = 0
        for string in pizzas_data:
            identificator, quantity_number = string.split('|')
            p = Pizza.objects.get(pk=identificator)
            total_order = p.price * float(quantity_number); 
            total_global += total_order
            order = Order(pizza=p, sale=sale_create, quantity=quantity_number, note="created by user", total=total_order)
            order.save()
            sale_create.order_set.add(order)
        sale_create.total = total_global
        sale_create.save()
    return render(request, 'client/confirm.html', {'sale': sale_create})



## vista usada para mostrar el historial de ventas
@login_required()
def history(request):
    client = request.user
    sales = Sale.objects.all().filter(client_id=client.id).order_by('-id');##TODO importante aqui se debe buscar por el cliente logueado
    return render(request, 'client/history.html', {'sales': sales})
    
@login_required()
def order_cancel(request, id):
    sale = Sale.objects.get(pk=id);
    sale.status = "CA";
    sale.save();
    return redirect('client:client_history')

skywalker/orders/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView)

from baseapp.models import (
    Order,
    Ingredient,
    PizzaBase,
    Pizza
)

from baseapp.mixin import TitleContentPageMixin

from .forms import (
    OrderForm,
    IngredientForm,
    PizzaBaseForm,
    PizzaForm
)

# ENTITY ORDER
#products-view
class PizzaBaseproductsViewList(TitleContentPageMixin, ListView):
    model = PizzaBase
    template_name = "orders/products-view.html"
    title_content = "orders"

class OrderList(TitleContentPageMixin, ListView):
    model = Order
    template_name = "orders/list.html"
    title_content = "orders"

class OrderCreation(TitleContentPageMixin, SuccessMessageMixin, CreateView):
    model = Order
    #success_url = reverse_lazy('orders:order_list')
    form_class = OrderForm
    template_name = "object/object_form.html"
    success_message = "Order create successfully"
    title_content = "New Order"

    def get_context_data(self, **kwargs):
        context = super(OrderCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create an ingredient"
        return context

class OrderDelete(TitleContentPageMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('orders:order_list')
    template_name = "orders/confirm_delete.html"
    title_content = "Delete Ingredient"

class OrderUpdate(TitleContentPageMixin, SuccessMessageMixin, UpdateView):
    model = Order
    success_url = reverse_lazy('orders:order_list')
    form_class = OrderForm
    template_name = "object/object_form.html"
    success_message = "Order edit successfully"
    title_content = "Update Order"

    def get_context_data(self, **kwargs):
        context = super(OrderUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Edit an ingredient"
        return context

class OrderDetail(TitleContentPageMixin,DetailView):
    model = Order
    template_name = "orders/detail.html"
    title_content = "Detail Order"


# ENTITY INGREDIENT
class IngredientList(TitleContentPageMixin, ListView):
    model = Ingredient
    template_name = "ingredient/list.html"
    title_content = "Ingredients"

class IngredientDetail(TitleContentPageMixin,DetailView):
    model = Ingredient
    template_name = "ingredient/detail_1.html"
    title_content = "Detail Ingredient"

class IngredientCreation(TitleContentPageMixin, SuccessMessageMixin, CreateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient create successfully"
    title_content = "New Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create an ingredient"
        return context

class IngredientUpdate(TitleContentPageMixin, SuccessMessageMixin, UpdateView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    form_class = IngredientForm
    template_name = "object/object_form.html"
    success_message = "Ingredient edit successfully"
    title_content = "Update Ingredient"

    def get_context_data(self, **kwargs):
        context = super(IngredientUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Edit an ingredient"
        return context

class IngredientDelete(TitleContentPageMixin, DeleteView):
    model = Ingredient
    success_url = reverse_lazy('pizza:ingredient_list')
    template_name = "ingredient/confirm_delete.html"
    title_content = "Delete Ingredient"

# ENTITY PIZZA BASE
class PizzaBaseList(TitleContentPageMixin,ListView):
    model = Pizza
    template_name = "orders/list_1.html"
    title_content = "Pizza List"

class PizzaBaseDetail(TitleContentPageMixin, DetailView):
    model = PizzaBase
    template_name = "orders/detail_1.html"
    title_content = "Detail Base Pizza"

class PizzaBaseCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza create successfully"
    title_content = "New Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    form_class = PizzaBaseForm
    template_name = "object/object_form.html"
    success_message = "Base Pizza edit successfully"
    title_content = "Update Base Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaBaseUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza base"
        return context


class PizzaBaseDelete(TitleContentPageMixin, DeleteView):
    model = PizzaBase
    success_url = reverse_lazy('pizza:pizzabase_list')
    template_name = "pizzaBase/confirm_delete.html"
    title_content = "Delete Base Pizza"

# ENTITY PIZZA
class PizzaList(TitleContentPageMixin,ListView):
    model = Pizza
    template_name = "pizza/list.html"
    title_content = "Pizzas"

class PizzaDetail(TitleContentPageMixin, DetailView):
    model = Pizza
    template_name = "pizza/detail.html"
    title_content = "Detail Pizza"

class PizzaCreation(TitleContentPageMixin, SuccessMessageMixin,CreateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza create successfully"
    title_content = "New Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaCreation, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaUpdate(TitleContentPageMixin, SuccessMessageMixin,UpdateView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    form_class = PizzaForm
    template_name = "object/object_form.html"
    success_message = "Pizza edit successfully"
    title_content = "Update Pizza"

    def get_context_data(self, **kwargs):
        context = super(PizzaUpdate, self).get_context_data(**kwargs)
        context['form_title'] = "Create a pizza"
        return context


class PizzaDelete(TitleContentPageMixin, DeleteView):
    model = Pizza
    success_url = reverse_lazy('pizza:pizza_list')
    template_name = "pizza/confirm_delete.html"
    title_content = "Delete Pizza"

skywalker/client/templates/client/base_purchases.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="M_Adnan">
    <title>Pizza SkyWalker</title>

    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="{% static "client/rs-plugin/css/settings.css" %}" media="screen"/>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "client/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "client/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "client/css/ionicons.min.css" %}" rel="stylesheet">
    <link href="{% static "client/css/main.css" %}" rel="stylesheet">
    <link href="{% static "client/css/style.css" %}" rel="stylesheet">
    <link href="{% static "client/css/responsive.css" %}" rel="stylesheet">

    <!-- JavaScripts -->
    <script src="{% static "client/js/modernizr.js" %}"></script>

    <!-- Online Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Alex+Brush' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,300,600,600italic,700italic,100'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300,800' rel='stylesheet' type='text/css'>

    {% block head %}
    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

{% block javascript %}
<script src="{% static "client/js/jquery-1.11.3.min.js" %}"></script>
<script src="{% static "client/js/bootstrap.min.js" %}"></script>
<script src="{% static "client/js/own-menu.js" %}"></script>
<script src="{% static "client/js/owl.carousel.min.js" %}"></script>
<!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
<script type="text/javascript" src="{% static "client/rs-plugin/js/jquery.tp.t.min.js" %}"></script>
<script type="text/javascript" src="{% static "client/rs-plugin/js/jquery.tp.min.js" %}"></script>
<script src="{% static "client/js/main.j" %}s"></script>

<!-- Begin Map Script-->
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script src="{% static "client/js/map.js" %}"></script>
{% endblock %}

</head>
<body>

<!-- Wrap -->
<div id="wrap">

    <!-- Top Bar -->
    <div class="top-bar tri-white-bottom">
        <div class="container">

            <!-- Pull Left -->
            <span class="numb">Domicilio (+57) 123-456-7890</span>
            <!-- Social Icons -->
            <div class="social"><a href="#."><i class="fa fa-facebook"></i></a> <a href="#."><i
                    class="fa fa-twitter"></i></a> <a href="#."><i class="fa fa-instagram"></i></a></div>
            <span class="time-ta">Abrimos desde las 10:00am - 11:00pm</span>

            <!-- Pull Right -->
            <div class="pull-right">
                <ul class="login-info">
                    <li>
                        <select class="selectpicker">
                            <option>ES</option>
                            <option>FR</option>
                        </select>
                    </li>
                    {% if user.is_authenticated %}
                        <li><a href="#"><small>{{ user.email }}</small></a></li>
                        <li><a href="{% url "client:client_history"  %}">History</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Cerrar sesión</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Acceder</a></li>
                        <li><a href="{% url 'account_signup' %}">Registrese</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% block body %}
    <!-- header -->
    

    <!--======= HOME MAIN SLIDER =========-->
    
    <!-- Content -->
    <div id="">

        <!-- Pizza Menu -->

        <!-- Our Restaurant -->
        <section class="inside-resturant tri-white-top padding-top-25 padding-bottom-20">
            <div class="container">
                <!--<div class="heading text-center"><span>{{ title }}</span>-->
                <!--    <hr>-->
                <!--    <i class="fa fa-bookmark-o"></i>-->
                <!--</div>-->
            
                <div class="center-block">
                    {% block content %}

                <!-- Heading Block -->

                <!-- Resturant Img -->
                

                <!-- Intro Text -->
                    <div class="about-text text-center">
                        <h1>from<br>
                            our <span>hearts</span></h1>
                        <p>We love Italy, we love italian food. Donec venenatis, turpis vel hendrerit interdum, dui
                            ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus
                            aliquet, elit magna vulputate. Bon Appetit!</p>
                    </div>
                    {% endblock %}
                </div>
            </div>
        </section>

        <!-- Testimonial -->
        
        <!-- Conatct Us -->
        
        <!-- MAP -->

    </div>
    

    {% endblock %}
    <!-- FOOTER -->
    
    <!-- RIGHTS -->
    <div style="padding: 0 0 100px; position: relative;">
    <section class="rights tri-white-top" style="position:fixed; left:0px; bottom:0px;">
        <div class="container">
            <p>Copyright 2017 Pizza Mia. All rights reserved for SaaS Universidad del Valle

            </p>
        </div>
    </section>
    </div>
</div>


</body>
</html>

skywalker/client/templates/client/confirm.html
{% extends 'client/base_purchases.html' %}

{% load static %}

{% block content %}

<h1>Detail Order</h1>

<div>
      <table class="table table-striped">
          <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Size</th>
              <th>Quantity</th>
              <th>Total</th>
          </tr>
    
{% for order in sale.order_set.all %}
<tr>
 <td>{{ order.pizza.pizza_base.name }}</td>   
 <td>{{ order.pizza.price }}</td>
 <td>{{ order.pizza.size }}</td>
 <td>{{ order.quantity }}</td>
 <td>{{ order.total  }}</td>
</tr>
{% endfor %}
<tr>
    <th colspan="4" class="tex-center">TOTAL</th>
    <th> {{ sale.total }}</th>
</tr>

  </table>
</div>

<div class="text-center">
    <div class="alert alert-info">
        Your order will be on the way in a few minutes
    </div>
    <br><br>
    <a href="{% url "client:client_index"  %}" class="btn btn-round btn-dark btn-small">Come Back</a>
</div>

<br>
<br>

{% endblock %}

skywalker/client/templates/client/history.html
{% extends 'client/index.html' %}

{% load static %}

{% block body %}

<h1 class="text-center">Sale History</h1>

<div style="heigth: 500px">
      <table class="table table-striped">
          <tr>
              <th>Date</th>
              <th>Total</th>
              <th class="text-center">Status</th>
              <th class="text-center"><i class="fa fa-cog"></i></th>
          </tr>
    
{% for sale in sales %}
<tr>
 <td>{{ sale.date }}</td>   
 <td><b>${{ sale.total }}</b></td>
 <td class="text-center"> {% if sale.status == "PE" %} PENDING {% elif sale.status  == "CA" %} CANCELED  {% else %} DONE {% endif %}</td>
 <td class="text-center"> 
 {% if sale.status == "PE" %}
 <a class=" btn-default" href="{% url "client:client_order_cancel" sale.id  %}"><i class="fa fa-close"></i> Cancel </a>
 {% else %}
 Done
 {% endif %}
 </td>
 
</tr>
{% endfor %}

  </table>
</div>

<div class="text-center">
    <a href="{% url "client:client_index"  %}" class="btn btn-round btn-dark btn-small">Come Back</a>
</div>

<br/>
<br/>

{% endblock %}

skywalker/client/templates/client/order.html
{% extends 'client/index.html' %}

{% load static %}

{% block javascript %}

<link href="{% static "client/css/smart_cart.css" %}" rel="stylesheet" type="text/css"> 
<script type="text/javascript" src="{% static "client/js/jquery-1.3.2.min.js" %}"></script>
<script type="text/javascript" src="{% static "client/js/jquery.smartCart-2.0.js" %}"></script>

{% endblock %}

{% block body %}

      <section class="pizza-menu tri-white-top padding-top-50 padding-bottom-50" id="our-menu">
            <div class="container">

                <!-- Heading Block -->
                <div class="heading text-center"><span>Placer de Elección</span>
                    <h3>Orden de Pizza</h3>
                    <hr>
                    <i class="fa fa-bookmark-o"></i></div>

             
<script type="text/javascript">
   
    $(document).ready(function(){
    	// Call Smart Cart    	
  		$('#SmartCart').smartCart();
		});
</script>

<form action='{% url "client:client_order_create" %}' method="post">
<!-- Smart Cart HTML Starts -->
{% csrf_token %}
<div id="SmartCart" class="scMain">

{% for pizza in pizzas %}

    <input type="hidden" pimage="{{ pizza.pizza_base.image.url }}" pprice="{{ pizza.price }}" pdesc="{{ pizza.pizza_base.description }}" pcategory="{{ pizza.size }}" pname="{{ pizza.pizza_base.name }}" pid="{{ pizza.id }}">
                      
{% endfor %}
</div>
<!-- Smart Cart HTML Ends -->
</form>
                <div>
        </section>


{% endblock %}